### ISSUE TITLE
Full semver coverage

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#127]
Currently, non-dev / release orb publishing doesn't accept all versions as specified in [Semantic Versioning 2.0.0](https://semver.org/) (e.g., `1.0.0-rc.1`). I would find it helpful if you had a guarantee that all semantic versions are published so that the decision if a semantic version is a `dev:`-version has not to be decided beforehand. One way to solve this would be the introduction of an additional argument in the CLI that redirects all "invalid"-flagged semantic versions to the `dev` branch instead of exiting with an error.

**Comment by ndintenfass** [comment]
Thanks for the note @matfax -- at the moment our thinking is we want that distinction to be a very purposeful choice, and the semantics of the separation (along with the differences in publishing security, mutability, and durability) are such that we wouldn't want there to be that kind of "hidden" flag. One pattern we've seen is people doing `dev:1.2.3` as the effective candidate for an orb that would then get published as `1.2.3`. We decided to not accept semver extended "labels" because it allows us to do nice things around determining latest and making it very simple to increment major/minor/patch directly.
