### ISSUE TITLE
What are orbs?

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [CircleCI-Public/config-preview-sdk#56]
I've seen references to this all over the documentation for `2.1`. Googling just sends me to https://github.com/CircleCI-Public/circleci-orbs which doesn't have an overview.

**Comment by JCMais** [comment]
See here https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/using-orbs.md

**Comment by sridhar-vadlamani-ck** [comment]
@JCMais I saw that. Couple of questions though. Where do I get these orbs from? What does it give me? How do I write them? Are they separate files ( as seems possible ) always, or do I define them in my `.circleci/config` file?

Some of these questions are probably very naive, but I can't seem to wrap my head around this concept.

**Comment by JCMais** [comment]
think on them like npm packages that you can depend on, for reuse on your `.config.yml`.

They are just packaged jobs.

This is a over simplification, but it was I understood on them.

You can write them inline, like said here https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/inline-orbs.md, but this is mostly going to be done when you are developing your own orbs.

**Comment by ndintenfass** [comment]
The docs have been substantially updated since this was first created, so I'm closing it. Feel free to add a new Issue if you think there's more we need for a first pass. Also, we'll soon be releasing a web-based way to browse the orb registry. You can also use `circleci orb list` to explore what's in the registry. View `circleci orb list -h` for more on usage.
