### ISSUE TITLE
Use snake or kebab case consistently

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#89]
`orb-tools` use kebab case for naming, while previously snake case was the standard for the yaml configs. Are there any thoughts from CircleCI on this?

**Comment by ndintenfass** [comment]
In general, our YAML uses snake case for historic reasons and because that's generally more common among many the languages/frameworks our users interact with (and seems to be more popular in other YAML config DSLs). Many of our initial orbs use kebab because that's more natural to some of the folks building them out. In general, we are not opinionated about this for orb authoring and consider it a matter of style. While not intentional, I do find that kebab can help visually differentiate between the core YAML syntax in our configuration from the imported orb elements in some cases. Curious: do you find this difference disconcerting, or are you just looking for guidance on how to name your orbs?

**Comment by ndintenfass** [comment]
(I'm going to close this for now, but feel free to comment)

**Comment by matfax** [comment]
@ndintenfass Thanks for letting me know. In general, I prefer kebab, it has a better appearance. However, if you use two styles in one file, it can be confusing. It opens a window for errors that are purely related to a mixup of `_` and `-`. But your argument is also comprehensible to distinguish core syntax from dynamic references.

In my orbs, I used snake case for the beginning. A general guidance, however, would be appreciated, maybe in the docs.
